### ISSUE TITLE
Support for js_of_ocaml and Bucklescript

### ISSUE THREAD

**Issue by copy** [OCamlPro/operf-micro#24]
Support for these alternative compilers would be nice, for comparisons between the two projects and the performance compared to native code.

Both projects produce code that can be run using nodejs, so the changes I believe are necessary are to stub out the code to read cpu cycles and to adapt the operf command line tool to invoke the individual compilers.

**Comment by chambart** [comment]
Sorry, but I won't have time to do that. But if someone comes with a PR, I would be quite happy to merge it.
